default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: webcam_development

  username: webcam
  #password:
  host: localhost
  port: 5432
  #schema_search_path: myapp,sharedapp,public
  #min_messages: notice

test:
  <<: *default
  database: webcam_test

production:
  <<: *default
  database: webcam_production
  username: webcam
  password: <%= ENV['WEBCAM_DATABASE_PASSWORD'] %>
